SELECT A.NHANVIEN_ID,
  A.LOAITB_ID,
  A.HUONG_DC,
  A.DATCOC_CSD,
  A.NGAY_HT,
  B1.MA_NV,
  B1.TEN_NV,
  B1.LOAIDV_ID_C2,
  NVL(B1.DONVI_ID_C2, -1) AS DONVI_ID_C2,
  NVL(B1.MA_DV_C2, 'KXD') AS MA_DV_C2,
  NVL(B1.TEN_DV_C2, 'KHONG XAC DINH') AS TEN_DV_C2,
  B1.LOAIDV_ID_C3,
  NVL(B1.DONVI_ID_C3, -1) AS DONVI_ID_C3,
  NVL(B1.MA_DV_C3, 'KXD') AS MA_DV_C3,
  NVL(B1.TEN_DV_C3, 'KHONG XAC DINH') AS TEN_DV_C3
FROM VW_BRCD_PTM_VNP010053_DT_DTC_PTM_COE_1 A
  LEFT JOIN VW_VNP010055_NHANVIEN_DONVI B1 ON A.NHANVIEN_ID = B1.NHANVIEN_ID