name: Telegram Bot CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Verify code runs successfully
        run: |
          # Create a .env file with dummy values for testing
          echo "BOT_TOKEN=dummy_token" > .env
          echo "ADMIN_ID=123456789" >> .env
          
          # Try importing the main modules to verify syntax
          python -c "import main; import src.config; import src.handlers.commands; import src.handlers.scheduler"
          
          # Validate main script structure (without actually starting the bot)
          python -c "from main import main; print('Main function loaded successfully')"